;;; excali-board-organize-test.el --- Board organization regression -*- lexical-binding: t; -*-
(require 'excali-board-test)

(defun excali-board-organize-test--arrow ()
  "Make a labeled arrow with a bound start and a free end."
  (let* ((one (excali-board-new-note "* Source"))
         (two (excali--make-element "rectangle" 600.0 60.0 '(width . 360.0) '(height . 220.0)))
         (arrow (excali--flowchart-arrow one two 'right)))
    (setq excali--elements (append excali--elements (list arrow)))
    (excali--unbind-end arrow 'end)
    (excali--set-text (excali--add-bound-text arrow) "supports")
    (excali--select (list arrow))
    (excali--commit)
    arrow))

(ert-deftest excali-board-organize-endpoint-creation-and-undo ()
  (excali-board-test--with
    (let* ((arrow (excali-board-organize-test--arrow))
           (id (excali--get arrow 'id))
           (start (excali--binding-element-id arrow 'start))
           (before (length excali--undo-stack))
           (card (excali-board-note-at-arrow-end))
           (card-id (excali--get card 'id)))
      (should (excali-board-note-p card))
      (should (equal card-id (excali--binding-element-id arrow 'end)))
      (should (equal start (excali--binding-element-id arrow 'start)))
      (should (equal "supports" (excali--get (excali--bound-text-of arrow) 'originalText)))
      (should (= (1+ before) (length excali--undo-stack)))
      (let ((old (excali--linear-global-points arrow)))
        (excali--put card 'y (+ 200 (excali--get card 'y)))
        (excali--touch card)
        (excali--update-bound-arrows (list card))
        (should-not (equal old (excali--linear-global-points arrow))))
      (excali-undo)
      (should-not (excali--live-element-by-id card-id))
      (should-not (excali--binding-element-id (excali--live-element-by-id id) 'end))
      (excali-redo)
      (should (equal card-id (excali--binding-element-id (excali--live-element-by-id id) 'end))))))

(ert-deftest excali-board-organize-endpoint-failure-rolls-back ()
  (excali-board-test--with
    (excali-board-organize-test--arrow)
    (let ((before (copy-tree excali--elements t))
          (history (length excali--undo-stack)))
      (cl-letf (((symbol-function 'excali--elbow-bind-end) (lambda (&rest _) (error "Injected"))))
        (should-error (excali-board-note-at-arrow-end)))
      (should (equal before excali--elements))
      (should (= history (length excali--undo-stack))))))

(ert-deftest excali-board-organize-free-end-hit-and-bound-rejection ()
  (excali-board-test--with
    (let* ((arrow (excali-board-organize-test--arrow))
           (point (car (last (excali--linear-global-points arrow)))))
      (should (eq 'end (excali-board-organize-free-end-at arrow point)))
      (should-not (excali-board-organize-free-end-at arrow '(0 . 0)))
      (excali-board-note-at-arrow-end)
      (excali--select (list arrow))
      (should-error (excali-board-note-at-arrow-end) :type 'user-error))))

(ert-deftest excali-board-organize-named-group-and-rename ()
  (excali-board-test--with
    (let* ((one (excali-board-new-note "* One"))
           (two (excali-board-new-note "* Two")))
      (excali--select (list one two))
      (let ((id (excali-board-name-group "Research")))
        (should (= 4 (length (excali--group-members id))))
        (should (= 1 (length (excali-board-organize--choices))))
        (excali-board-rename-group "Ideas")
        (should (string-match-p "Ideas" (caar (excali-board-organize--choices))))
        (excali-undo)
        (should (string-match-p "Research" (caar (excali-board-organize--choices))))
        (excali-ungroup)
        (should-not (excali-board-organize--choices))))))

(ert-deftest excali-board-organize-region-keeps-links-and-releases-on-delete ()
  (excali-board-test--with
    (let* ((one (excali-board-new-note "* One"))
           (two (excali-board-new-note "* Two")))
      (excali--select (list one two))
      (let ((arrow (excali-board-connect "edge")))
        (excali--select (list one two))
        (let* ((frame (excali-board-create-region "Project"))
               (id (excali--get frame 'id)))
          (should (excali--frame-p frame))
          (should (= 6 (length (excali--frame-children frame))))
          (should (equal id (excali--get arrow 'frameId)))
          (let ((old (excali--get one 'x)))
            (excali--nudge 30 0)
            (should (= (+ old 30) (excali--get one 'x))))
          (excali--select (list frame))
          (excali-delete-selected)
          (should-not (excali--get one 'frameId))
          (should-not (excali--get two 'isDeleted))
          (should (equal (excali--get two 'id) (excali--binding-element-id arrow 'end))))))))

(ert-deftest excali-board-organize-serialization-preserves-names ()
  (excali-board-test--with
    (let ((one (excali-board-new-note "* One"))
          (two (excali-board-new-note "* Two")))
      (excali--select (list one two))
      (excali-board-name-group "Named")
      (excali-board-create-region "Region")
      (setq excali--file (expand-file-name "organized.excalidraw" dir))
      (excali-board-save)
      (let ((doc (excali--restore-doc (excali--read-file excali--file))))
        (setq excali--elements (append (alist-get 'elements doc) nil))
        (should (= 2 (length (excali-board-organize--choices))))
        (should (seq-some (lambda (e) (equal "Region" (excali--get e 'name)))
                          excali--elements))))))

(ert-deftest excali-board-organize-start-endpoint-and-point-editor-exit ()
  (excali-board-test--with
    (let* ((arrow (excali-board-organize-test--arrow))
           (old-card (excali--live-element-by-id (excali--binding-element-id arrow 'start))))
      (excali--unbind-end arrow 'start)
      (excali--elbow-bind-end arrow 'end old-card)
      (setq excali--editing-linear arrow excali--selected-points '(0))
      (let ((card (excali-board-note-at-arrow-end 'start "* Before")))
        (should (equal (excali--get card 'id) (excali--binding-element-id arrow 'start)))
        (should (equal (excali--get old-card 'id) (excali--binding-element-id arrow 'end)))
        (should-not excali--editing-linear)
        (should-not excali--selected-points)
        (should (eq card (car excali--selection)))))))

(ert-deftest excali-board-organize-region-refuses-partial-group-and-nesting ()
  (excali-board-test--with
    (let ((one (excali-board-new-note "* One"))
          (two (excali-board-new-note "* Two")))
      (excali--select (list one two))
      (excali-board-name-group "Whole")
      (excali--select (list one))
      (should-error (excali-board-create-region "Partial") :type 'user-error)
      (excali--select (list one two))
      (excali-board-create-region "Whole")
      (should-error (excali-board-create-region "Nested") :type 'user-error))))

(ert-deftest excali-board-organize-straight-arrow-keeps-label ()
  (excali-board-test--with
    (let ((arrow (excali--make-element
                  "arrow" 30.0 50.0 '(width . 180.0) '(height . 0.0)
                  '(points . [[0.0 0.0] [180.0 0.0]]))))
      (setq excali--elements (list arrow))
      (excali--set-text (excali--add-bound-text arrow) "Label")
      (excali--select (list arrow))
      (excali--commit)
      (let ((card (excali-board-note-at-arrow-end 'end)))
        (should-not (excali--elbow-p arrow))
        (should (equal (excali--get card 'id) (excali--binding-element-id arrow 'end)))
        (should (equal "Label" (excali--get (excali--bound-text-of arrow) 'originalText)))))))

(provide 'excali-board-organize-test)
