;;; excali-dsl-parser.el --- Excali DSL lexer and styles -*- lexical-binding: t; -*-
;; Copyright (C) 2026 yibie
;; SPDX-License-Identifier: GPL-3.0-or-later
;;; Commentary:
;; A deliberately small, non-evaluating parser for .excalidsl.
;;; Code:
(require 'cl-lib)
(require 'subr-x)
(define-error 'excali-dsl-error "Excali DSL error")
(defvar excali-dsl--tokens)

(defun excali-dsl--fail (token format-string &rest args)
  "Report FORMAT-STRING with ARGS at TOKEN's source location."
  (signal 'excali-dsl-error
          (list (or (nth 2 token) 1) (apply #'format format-string args)
                (or (nth 3 token) 1))))

(defun excali-dsl-error-message (err)
  "Format DSL error ERR including its line and column."
  (format "line %d, column %d: %s" (nth 1 err) (or (nth 3 err) 1) (nth 2 err)))

(defun excali-dsl--lex (source)
  "Tokenize SOURCE without using the Lisp reader."
  (with-temp-buffer
    (insert source) (goto-char (point-min))
    (let (tokens)
      (while (not (eobp))
        (let ((line (line-number-at-pos)) (col (1+ (current-column))))
          (cond
           ((looking-at "[ \t\r]+") (goto-char (match-end 0)))
           ((looking-at "//[^\n]*") (goto-char (match-end 0)))
           ((looking-at "\n") (push (list 'newline "\n" line col) tokens) (forward-char))
           ((looking-at "->") (push (list 'word "->" line col) tokens) (forward-char 2))
           ((looking-at "[{}:;]")
            (push (list 'punct (match-string 0) line col) tokens) (forward-char))
           ((eq (char-after) ?\")
            (forward-char)
            (let (chars closed)
              (while (and (not closed) (not (eobp)))
                (let ((c (char-after)))
                  (forward-char)
                  (cond ((eq c ?\") (setq closed t))
                        ((eq c ?\n) (excali-dsl--fail (list nil nil line col) "Raw newline in string"))
                        ((eq c ?\\)
                         (let* ((e (char-after))
                                (v (cdr (assq e '((?\" . ?\") (?\\ . ?\\) (?n . ?\n) (?t . ?\t))))))
                           (unless v (excali-dsl--fail (list nil nil line col) "Unknown string escape"))
                           (forward-char) (push v chars)))
                        (t (push c chars)))))
              (unless closed (excali-dsl--fail (list nil nil line col) "Unclosed string"))
              (push (list 'string (apply #'string (nreverse chars)) line col) tokens)))
           ((looking-at "[A-Za-z_][A-Za-z0-9_-]*\\(?:\\.[A-Za-z_][A-Za-z0-9_-]*\\)*")
            (let ((start (point)) (end (match-end 0)))
              ;; A hyphen before > belongs to ->, not the identifier.
              (when (and (eq (char-before end) ?-) (eq (char-after end) ?>))
                (setq end (1- end)))
              (push (list 'word (buffer-substring-no-properties start end) line col) tokens)
              (goto-char end)))
           ((looking-at "-?[0-9]+\\(?:\\.[0-9]+\\)?")
            (push (list 'number (string-to-number (match-string 0)) line col) tokens)
            (goto-char (match-end 0)))
           (t (excali-dsl--fail (list nil nil line col) "Unexpected character %c" (char-after))))))
      (nreverse (cons (list 'eof nil (line-number-at-pos) (1+ (current-column))) tokens)))))

(defun excali-dsl--take (&optional value kind)
  "Take a token, optionally requiring VALUE and KIND."
  (let ((tok (pop excali-dsl--tokens)))
    (when (or (eq (car tok) 'eof)
              (and value (not (equal (cadr tok) value)))
              (and kind (or (not (eq (car tok) kind))
                            (and (eq kind 'word) (equal (cadr tok) "->")))))
      (excali-dsl--fail tok "Expected %s, got %s" (or value kind) (or (cadr tok) "end of input")))
    tok))

(defun excali-dsl--at (value)
  "Whether the next token has VALUE."
  (equal (cadar excali-dsl--tokens) value))

(defun excali-dsl--newlines ()
  "Consume newlines."
  (while (eq (caar excali-dsl--tokens) 'newline) (pop excali-dsl--tokens)))

(defun excali-dsl--properties ()
  "Read a trailing style block as (KEY VALUE TOKEN VALUE-TOKEN) entries."
  (excali-dsl--take "{")
  (excali-dsl--newlines)
  (let (props)
    (while (not (excali-dsl--at "}"))
      (let* ((tok (excali-dsl--take nil 'word)) (key (cadr tok)))
        (when (assoc key props) (excali-dsl--fail tok "Duplicate property %s" key))
        (excali-dsl--take ":")
        (let ((value (excali-dsl--take)))
          (unless (memq (car value) '(word string number))
            (excali-dsl--fail value "Expected a property value"))
          (push (list key (cadr value) tok value) props)))
      (unless (or (excali-dsl--at "}") (excali-dsl--at ";")
                  (eq (caar excali-dsl--tokens) 'newline))
        (excali-dsl--fail (car excali-dsl--tokens) "Separate properties with a newline or semicolon"))
      (when (excali-dsl--at ";") (pop excali-dsl--tokens))
      (excali-dsl--newlines))
    (excali-dsl--take "}")
    (nreverse props)))

(defun excali-dsl-parse (source)
  "Parse SOURCE into a list of statement plists with source locations."
  (let ((excali-dsl--tokens (excali-dsl--lex source)) result)
    (excali-dsl--newlines)
    (while (not (eq (caar excali-dsl--tokens) 'eof))
      (let* ((start (excali-dsl--take nil 'word))
             (kind (cadr start)) (id (excali-dsl--take nil 'word))
             (s (list :kind kind :id (cadr id) :token start :line (nth 2 start)))
             placements sides done)
        (unless (= (nth 3 start) 1) (excali-dsl--fail start "Statements must start at column 1"))
        (unless (member kind '("node" "edge" "style" "default"))
          (excali-dsl--fail start "Unknown statement %s" kind))
        (when (equal kind "edge")
          (excali-dsl--take "->")
          (setq s (plist-put s :target (excali-dsl--take nil 'word))))
        (when (and (member kind '("node" "edge")) (eq (caar excali-dsl--tokens) 'string))
          (setq s (plist-put s :label (cadr (excali-dsl--take)))))
        (while (not done)
          (cond
           ((eq (caar excali-dsl--tokens) 'newline)
            ;; Only one newline followed by indentation continues a header.
            (if (and (not (memq (car (cadr excali-dsl--tokens)) '(newline eof)))
                     (> (nth 3 (cadr excali-dsl--tokens)) 1))
                (pop excali-dsl--tokens)
              (setq done t)))
           ((eq (caar excali-dsl--tokens) 'eof) (setq done t))
           ((excali-dsl--at "{")
            (setq s (plist-put s :props (excali-dsl--properties)) done t)
            (unless (memq (caar excali-dsl--tokens) '(newline eof))
              (excali-dsl--fail (car excali-dsl--tokens) "Nothing may follow a style block")))
           ((equal kind "node")
            (let* ((tok (excali-dsl--take nil 'word)) (op (cadr tok)))
              (pcase op
                ((or "left" "right") (excali-dsl--take "of"))
                ("level" (excali-dsl--take "with"))
                ((or "above" "below") nil)
                (_ (excali-dsl--fail tok "Unknown placement %s" op)))
              (push (list op (excali-dsl--take nil 'word) tok) placements)))
           ((equal kind "edge")
            (let* ((tok (excali-dsl--take nil 'word)) (key (cadr tok)))
              (unless (member key '("from" "to")) (excali-dsl--fail tok "Expected from: or to:"))
              (when (assoc key sides) (excali-dsl--fail tok "Duplicate %s side" key))
              (excali-dsl--take ":")
              (let ((side (excali-dsl--take nil 'word)))
                (unless (member (cadr side) '("top" "right" "bottom" "left"))
                  (excali-dsl--fail side "Unknown side %s" (cadr side)))
                (push (cons key (cadr side)) sides))))
           (t (excali-dsl--fail (car excali-dsl--tokens) "Expected a style block"))))
        (when (and (member kind '("style" "default")) (not (plist-member s :props)))
          (excali-dsl--fail start "Style/default requires a block"))
        (push (append s (list :placements (nreverse placements) :sides sides)) result))
      (excali-dsl--newlines))
    (nreverse result)))

(defconst excali-dsl--property-schema
  '(("shape" "shape" node "rectangle" "ellipse" "diamond")
    ("stroke" "strokeColor" both color)
    ("fill" "backgroundColor" node fill)
    ("stroke-width" "strokeWidth" both positive)
    ("stroke-style" "strokeStyle" both "solid" "dashed" "dotted")
    ("fill-style" "fillStyle" node "solid" "hachure" "cross-hatch" "zigzag")
    ("roughness" "roughness" both 0 1 2)
    ("roundness" "roundness" node "sharp" "round")
    ("opacity" "opacity" both percent)
    ("font" "font" both "hand" "sans" "mono")
    ("font-size" "fontSize" both positive)
    ("text-color" "textColor" both color)
    ("text-align" "textAlign" both "left" "center" "right")
    ("routing" "routing" edge "straight" "elbow"))
  "Public name, native key, target and allowed values.")

(defun excali-dsl--validate-props (props kind &optional allow-style)
  "Validate PROPS for KIND, optionally ALLOW-STYLE references."
  (dolist (p props)
    (let* ((key (car p)) (value (cadr p)) (tok (nth 2 p)) (vtoken (nth 3 p))
           (spec (assoc key excali-dsl--property-schema)) (values (nthcdr 3 spec)))
      (if (equal key "style")
          (unless (and allow-style (eq (car vtoken) 'word)
                       (not (string-match-p "\\." value)))
            (excali-dsl--fail tok "Only elements may reference one named style"))
        (unless spec (excali-dsl--fail tok "Unknown property %s" key))
        (unless (or (eq kind 'both) (eq (nth 2 spec) 'both) (eq kind (nth 2 spec)))
          (excali-dsl--fail tok "%s is not valid on %s" key kind))
        (unless
            (pcase (car values)
              ((or 'color 'fill)
               (or (and (eq (car values) 'fill) (equal value "none") (eq (car vtoken) 'word))
                   (and (eq (car vtoken) 'string)
                        (string-match-p "\\`#\\(?:[[:xdigit:]]\\{3\\}\\|[[:xdigit:]]\\{6\\}\\)\\'" value))))
              ('positive (and (numberp value) (> value 0) (< value 1.0e+100)))
              ('percent (and (numberp value) (<= 0 value 100)))
              (_ (and (member value values) (not (eq (car vtoken) 'string)))))
          (excali-dsl--fail vtoken "Invalid value for %s: %s" key value))))))

(defun excali-dsl--native-props (props)
  "Convert validated PROPS into the native style alist."
  (cl-loop for (key value) in props unless (equal key "style")
           collect (cons (nth 1 (assoc key excali-dsl--property-schema))
                         (pcase key
                           ("font" (cdr (assoc value '(("hand" . 5) ("sans" . 6) ("mono" . 8)))))
                           ("roundness" (if (equal value "sharp") 0 1))
                           ("fill" (if (equal value "none") "transparent" value))
                           (_ value)))))
(provide 'excali-dsl-parser)
;;; excali-dsl-parser.el ends here
